apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyfastapi-deployment
  labels:
    app: tinyfastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyfastapi
  template:
    metadata:
      labels:
        app: tinyfastapi
    spec:
      containers:
      - image: recofilmsmlopsoct2023/tinyfastapi:latest
        name: tinyfastapi
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8002
